#!/usr/bin/env bash

# ––– •Alias START here• –––
# better view
alias cp='cp -iv'                # Preferred 'cp' implementation
alias mv='mv -iv'                # Preferred 'mv' implementation
alias mkdir='mkdir -pv'          # Preferred 'mkdir' implementation
alias ll='ls -FGlAhp'            # Preferred 'ls' implementation
alias e='exa --classify'         # preferred "exa" impl
alias el='exa --long --classify --git' # preferred "exa" impl
alias ell='exa --long --classify --git' # preferred "exa" impl
alias less='less -FSRXc'         # Preferred 'less' implementation
# Open program faster
alias suq='sudo poweroff'
alias r='ranger'
alias d='date && cal'
alias z='clear'
alias sc='screen'
alias em='emacsclient'
alias emt='emacsclient -t'
alias nf='neofetch'
alias tr='trans :ar'
alias pping='prettyping'
# mpv short cut
alias mpvs='mpv --sub-file'
alias mpvm='mpv --ytdl-format=18'
alias mpvms='mpv --ytdl-format=18 --sub-file'
alias setkey='setxkbmap -layout de,ar -variant qwertz_neo, -option grp:alt_shift_toggle'
alias usbm='sudo mount -o uid=1000 /dev/sdb /home/master/sdb/'
alias usbum='sudo umount /dev/sdb'
# Git alias and color
alias g='grc git'
alias ga='git add'
alias gb='git branch'
alias gcm!!!='git add .; and git commit -m "Update"; and git push'
alias gco='git checkout'
alias gcob='git checkout -b'
alias gcod='git checkout development'
alias gi='gitignore'
alias gm='git merge'
alias gpl='git pull'
alias gps='git push'
alias gpsu='git push -u origin master'
alias gs='git status'
alias gc='grc git clone'
alias gd='git diff'
# Magic Git
alias magit='emacsclient -c -n -e "(progn (magit-status) (delete-other-windows))"'
### Colorize program
## with grc
alias ping='grc ping'
alias traceroute='grc traceroute'
alias gcc='grc gcc'
alias make='grc make'
alias netstat='grc netstat'
alias diff='grc diff'
alias last='grc last'
alias ldap='grc ldap'
alias cvs='grc cvs'
## with colout
alias colorshow='for c in {0..255}; do echo "$c color" | colout "color" $c; done'
alias aptup='sudo apt update | colout "Get" 118 | colout "Ign" 124 | colout "Hit" 226 | colout "^.*see.*$" 51 | colout "\d* .B | \d*.\d* .B" 3 | colout "http.+ " 6'
alias aptin='sudo apt install'
aptse ()
{
    apt search $1 | colout "^.*installed.*" 242 | colout "(^.*)/.*" 2 | less
}

aptsh ()
{
    # Second Line capture any size
    # Third line capture any link
    apt show $1 | colout "Version" 4 |colout "^Installed-Size" 2 | colout "^Download-Size" 2  \
        | colout "\d* .B | \d*.\d* .B" 3 \
        | colout "http.+" 6 \
        | less
}

downp ()
{
    wget --recursive --no-clobber --page-requisites --html-extension --convert-links --domains "$1" --no-parent $1;
}
# ––– •Alias END here• –––
